---
- name: Configure shell for all hosts
  hosts: k3s_vms

  tasks:
    - name: Install needed packages for k3s ansible
      become: true
      ansible.builtin.package:
        name:
          - python3-apt
          - wget
        state: present

    - name: Install needed packages for longhorn
      #https://longhorn.io/docs/1.7.2/deploy/install/
      become: true
      ansible.builtin.package:
        name:
          - open-iscsi
          #- bash
          - curl
          #- findmnt
          #- grep
          #- awk
          # To install 'blkid'
          - util-linux
          #- lsblk
        state: present

    - name: Create ansible tmp dir
      become: true
      ansible.builtin.file:
        path: /root/.ansible/tmp
        state: directory
        mode: '0755'
