* Links

- [[https://robomongo.org/]]
- [[https://docs.mongodb.com/manual/]]

- Data types: https://docs.mongodb.com/manual/reference/bson-types/

* Get started

In the same directory as this document I have prepared a [[./docker-compose.yml][docker-compose.yml]] file
which you can start with:

#+BEGIN_SRC bash
docker-compose up -d
# You can later remove it with:
docker-compose down
# or if you also want to remove all data until next time
docker-compose down -v
#+END_SRC

When the container is running you can connect to it with:

#+BEGIN_SRC bash
docker exec -it mongodb bash
#+END_SRC

followed by (inside the container)

#+BEGIN_SRC bash
mongo -u root -p pass12345 --authenticationDatabase admin
#+END_SRC

Alternatively you can just run

#+BEGIN_SRC bash
docker exec -it mongodb mongo -u root -p pass12345 --authenticationDatabase admin
#+END_SRC

* Overview commands

| Command                | Description                                         |
|------------------------+-----------------------------------------------------|
| ~show databases~       | Show the available databases                        |
| ~use <database>~       | Switch to ~<database>~                              |
| ~db.getName()~ or ~db~ | Show the name of the currently selected database    |
| ~show collections~     | Show collections in the currently selected database |
| ~db.dropDatabase()~    | Drops the currently selected database               |

** Help

To see the list of help for methods you can use on the ~db~ object, call the
~db.help()~ method.

To see the list of help for methods you can use on the ~db.collection~ object,
call the ~db.collection.help()~ method.

To see the implementation of a method in the shell, type the method name without
the parenthesis. E.g.

#+BEGIN_SRC js
db.collection.count
#+END_SRC

* Get started

Logon to the mongodb instance as explained above. Switch to the ~examples~
database:

#+BEGIN_SRC
use examples
#+END_SRC

The database will be created when we store data in this database (such as
creating our first collection). To verify that we are in the correct database,
type ~db~.

If a collection does not exist, MongoDB creates the collection when you first
store data for that collection. We will use ~db.collection.insertMany()~ to
insert new documents (data records) into a collection we will call ~inventory~.
You can run ~show collections~ to verify that it doesn't exists before inserting
the documents. Insert the documents:

#+BEGIN_SRC js
db.inventory.insertMany([
   { item: "journal", qty: 25, status: "A", size: { h: 14, w: 21, uom: "cm" }, tags: [ "blank", "red" ] },
   { item: "notebook", qty: 50, status: "A", size: { h: 8.5, w: 11, uom: "in" }, tags: [ "red", "blank" ] },
   { item: "paper", qty: 10, status: "D", size: { h: 8.5, w: 11, uom: "in" }, tags: [ "red", "blank", "plain" ] },
   { item: "planner", qty: 0, status: "D", size: { h: 22.85, w: 30, uom: "cm" }, tags: [ "blank", "red" ] },
   { item: "postcard", qty: 45, status: "A", size: { h: 10, w: 15.25, uom: "cm" }, tags: [ "blue" ] }
]);

// MongoDB adds an _id field with an ObjectId value if the field is not present in the document
#+END_SRC

The operation returns a document that contains the acknowledgement indicator and
an array that contains the _id of each successfully inserted documents.

To look at the data we just inserted we can run the following command:

#+BEGIN_SRC js
db.inventory.find({})
// or
db.inventory.find()
// or for pretty print
db.inventory.find({}).pretty()
#+END_SRC

For an equality match (i.e. ~<field>~ equals ~<value>~), specify ~<field>: <value>~
in the /query filter document/ and pass to the ~db.collection.find()~. Run the
following queries and see what happens (add ~.pretty()~ in the end for better
readability):

#+BEGIN_SRC js
db.inventory.find( { status: "D" } );
db.inventory.find( { qty: 0 } );
// In the following query both statements must be true
db.inventory.find( { qty: 0, status: "D" } );
// You can query for a field nested inside the "size" document
db.inventory.find( { "size.uom": "in" } )
// You can check the equality of the whole size field object
// Note that everything must match including field order
// Compare these (only the first one will match):
db.inventory.find( { size: { h: 14, w: 21, uom: "cm" } } )
db.inventory.find( { size: { w: 21, h: 14, uom: "cm" } } )
// Look if the tags array contains "red"
db.inventory.find( { tags: "red" } )
// Look if the tags array is exactly equal to (including order)
db.inventory.find( { tags: [ "red", "blank" ] } )
#+END_SRC

The queries above returns all fields in each document. We can limit that by
passing a /projection document/ to the ~db.collection.find()~ query. In the
projection document, specify:

- ~<field>: 1~ to include a field in the returned document
- ~<field>: 0~ to exclude a field in the returned document

The ~_id~ field is included by default but we can exclude it if we want to. In
the following example the first parameter is the /query filter document/ and the
second parameter is the /projection document/.

#+BEGIN_SRC js
// Return _id, item and status
db.inventory.find( { }, { item: 1, status: 1 } );
// Return item, status and size.h
db.inventory.find( { }, { _id: 0, item: 1, status: 1, "size.h": 1 } );
// Return item, status and size.h where the status is D
db.inventory.find( {status: "D"} , { _id: 0, item: 1, status: 1, "size.h": 1 } );
#+END_SRC

* Documents
** Data types

https://docs.mongodb.com/manual/reference/bson-types/

** Field names

The field name ~_id~ is reserved for use as a primary key; its value must be
unique in the collection, is immutable, and may be of any type other than an
array.

Field names *cannot* contain the ~null~ character.

Top-level field names *cannot* start with the dollar sign (~$~) character.

** Dot notation
*** Arrays

To specify or access an element of an array by the zero-based index position,
concatenate the array name with the dot (~.~) and zero-based index position, and
enclose in quotes.

#+BEGIN_SRC js
"<array>.<index>"
// or
"tags.1" // for the second tag
#+END_SRC

*** Embedded Documents

To specify or access a field of an embedded document with dot notation,
concatenate the embedded document name with the dot (~.~) and the field name,
and enclose in quotes:

#+BEGIN_SRC js
"<embedded document>.<field>"
// or
"size.h" // for the h field in the size document
#+END_SRC

** Limitations
*** Size limit

The maximum BSON document size is 16 megabytes.

*** Document field order

MongoDB preserves the order of the document fields following write operations
except for the following cases:

- The ~_id~ field is always the first field in the document.
- Updates that include renaming of field names may result in the reordering of fields in the document.

** Query Filter Documents

Query filter documents specify the conditions that determine which records to
select for read, update, and delete operations. E.g:

#+BEGIN_SRC
{
  <field1>: <value1>,
  <field2>: { <operator>: <value> },
  ...
}
#+END_SRC

** Update Specification Documents

Update specification documents use update operators to specify the data
modifications to perform on specific fields during an db.collection.update()
operation.

#+BEGIN_SRC
{
  <operator1>: { <field1>: <value1>, ... },
  <operator2>: { <field2>: <value2>, ... },
  ...
}
#+END_SRC

** Index Specification Documents

Index specification documents define the field to index and the index type.

* CRUD
** Insert documents

Mainly two methods:

- [[https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/#db.collection.insertOne][db.collection.insertOne()]]: Inserts single document
- [[https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/#db.collection.insertMany][db.collection.insertMany()]]: Inserts multiple documents

Insert one document:

#+BEGIN_SRC js
use insertsexample
db.inventory.insertOne(
   { item: "canvas", qty: 100, tags: ["cotton"], size: { h: 28, w: 35.5, uom: "cm" } }
)
#+END_SRC

Query that document:

#+BEGIN_SRC js
db.inventory.find( { item: "canvas" } )
#+END_SRC

Insert multiple documents:

#+BEGIN_SRC js
db.inventory.insertMany([
   { item: "journal", qty: 25, tags: ["blank", "red"], size: { h: 14, w: 21, uom: "cm" } },
   { item: "mat", qty: 85, tags: ["gray"], size: { h: 27.9, w: 35.5, uom: "cm" } },
   { item: "mousepad", qty: 25, tags: ["gel", "blue"], size: { h: 19, w: 22.85, uom: "cm" } }
])
#+END_SRC

To get all inserted documents back pretty printed:

#+BEGIN_SRC js
db.inventory.find().pretty()
#+END_SRC

* To check

- Write concerns

