services:
  ubuntu0:
    image: ubuntuansibletarget:latest
    ports:
      - "1022:22"
    init: true
  ubuntu1:
    image: ubuntuansibletarget:latest
    ports:
      - "1122:22"
    init: true

  fedora0:
    image: fedoraansibletarget:latest
    ports:
      - "2022:22"
    init: true
  fedora1:
    image: fedoraansibletarget:latest
    ports:
      - "2122:22"
    init: true
