#!/bin/bash

SCRIPT_NAME=$(realpath "$0")

while :; do
    read -ep "Enter a unique server number (0-39) or 'n' to continue without configuring the vm for now: " number
    if [ "$number" == 'n' ]; then
        echo "No configuration will be done"
        exit
    fi
    if [[ ! $number =~ ^[[:digit:]]+$ ]]; then
        echo "The provided value was not a positive integer"
        continue
    fi
    if (( number > 39 )); then
        echo "Number was greater than 39"
        continue
    fi
    break
done
echo "VM number is:              ${number}"
while :; do
    read -p 'Generate new ssh host keys (y/n): ' gen_ssh_key
    if [[ "$gen_ssh_key" =~ ^(y|n)$ ]]; then
        break
    fi
done

echo
new_hostname=$(printf "debian-%02d" $number)
echo "Hostname will be set to:   $new_hostname"
new_ip="192.168.1.$(( 200 + number ))"
echo "IP address will be set to: $new_ip"
if [ "$gen_ssh_key" == 'y' ]; then
    echo "New ssh host keys will be generated"
else
    echo "New ssh host keys will NOT be generated"
fi

read -s -p "Press enter to confirm the new settings or Ctrl-C to exit"

if [ $? -ne 0 ]; then
    echo
    echo "Exited.."
    exit
fi

if [ "$gen_ssh_key" == 'y' ]; then
    rm /etc/ssh/ssh_host_*
    ssh-keygen -A
fi

echo "$new_hostname" > /etc/hostname

cat << END_OF_NETPLAN_CONFIG > /etc/netplan/network.yaml
network:
  version: 2
  ethernets:
    ens18:
      dhcp4: no
      dhcp6: no
      addresses:
      - ${new_ip}/24
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
        search: []
END_OF_NETPLAN_CONFIG

netplan generate
rm "$SCRIPT_NAME"
reboot
